# Generated by Django 3.2.9 on 2021-12-14 12:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('text', tinymce.models.HTMLField()),
                ('pub_date', models.CharField(default='01.01.2021', max_length=20)),
                ('post_image', models.ImageField(default='-', upload_to='static/uploads')),
            ],
        ),
    ]
