# Generated by Django 3.2.9 on 2021-12-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.CharField(default='01.01.2021', max_length=20),
        ),
    ]
