# Generated by Django 3.2.9 on 2021-12-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='#', upload_to='static/uploads'),
        ),
    ]
